version: 1
accounts:
- name: zack
  coins:
  - 300000000ebc
- name: deven
  coins:
  - 100000000ebc
faucet:
  name: zack
  coins:
  - 10000ebc
client:
  typescript:
    path: ts-client
  composables:
    path: vue/src/composables
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    mint:
      params:
        mint_denom: ebc
    staking:
      params:
        bond_denom: ebc
  chain_id: exabits
validators:
- name: zack
  bonded: 150000000ebc
