version: 1
accounts:
    - name: zack
      coins: ["300000000ebc"]
    - name: deven
      coins: ["100000000ebc"]
faucet:
    name: zack
    coins: ["10000ebc"]
client:
    openapi:
        path: docs/static/openapi.yml
validators:
    - name: zack
      bonded: "150000000ebc"
genesis:
    chain_id: "exabits"
    app_state:
        staking:
            params:
                bond_denom: "ebc"
        mint:
            params:
                mint_denom: "ebc"
