// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgUpdateDevices } from "./types/exabits/computing/tx";
import { MsgDeleteDevices } from "./types/exabits/computing/tx";
import { MsgCreateDevices } from "./types/exabits/computing/tx";

import { Devices as typeDevices} from "./types"
import { Params as typeParams} from "./types"

export { MsgUpdateDevices, MsgDeleteDevices, MsgCreateDevices };

type sendMsgUpdateDevicesParams = {
  value: MsgUpdateDevices,
  fee?: StdFee,
  memo?: string
};

type sendMsgDeleteDevicesParams = {
  value: MsgDeleteDevices,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateDevicesParams = {
  value: MsgCreateDevices,
  fee?: StdFee,
  memo?: string
};


type msgUpdateDevicesParams = {
  value: MsgUpdateDevices,
};

type msgDeleteDevicesParams = {
  value: MsgDeleteDevices,
};

type msgCreateDevicesParams = {
  value: MsgCreateDevices,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgUpdateDevices({ value, fee, memo }: sendMsgUpdateDevicesParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateDevices: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgUpdateDevices({ value: MsgUpdateDevices.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateDevices: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDeleteDevices({ value, fee, memo }: sendMsgDeleteDevicesParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDeleteDevices: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgDeleteDevices({ value: MsgDeleteDevices.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDeleteDevices: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreateDevices({ value, fee, memo }: sendMsgCreateDevicesParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateDevices: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateDevices({ value: MsgCreateDevices.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateDevices: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgUpdateDevices({ value }: msgUpdateDevicesParams): EncodeObject {
			try {
				return { typeUrl: "/exabits.computing.MsgUpdateDevices", value: MsgUpdateDevices.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateDevices: Could not create message: ' + e.message)
			}
		},
		
		msgDeleteDevices({ value }: msgDeleteDevicesParams): EncodeObject {
			try {
				return { typeUrl: "/exabits.computing.MsgDeleteDevices", value: MsgDeleteDevices.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDeleteDevices: Could not create message: ' + e.message)
			}
		},
		
		msgCreateDevices({ value }: msgCreateDevicesParams): EncodeObject {
			try {
				return { typeUrl: "/exabits.computing.MsgCreateDevices", value: MsgCreateDevices.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateDevices: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						Devices: getStructure(typeDevices.fromPartial({})),
						Params: getStructure(typeParams.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			ExabitsComputing: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;